(deftheme selenized
  "selenized theme")

(let ((bg0 "#103c48")
      (bg1 "#184956")
      (bg2 "#2d5b69")
      (dim0 "#72898f")
      (fg0 "#adbcbc")
      (fg1 "#cad8d9")
      (darkRed "#fa5750")
      (darkGreen "#75b938")
      (darkYellow "#dbb32d")
      (darkBlue "#4695f7")
      (darkMagenta "#f275be")
      (darkCyan "#41c7b9")
      (lightRed "#ff665c")
      (lightGreen "#84c747")
      (lightYellow "#ebc13d")
      (lightBlue "#58a3ff")
      (lightMagenta "#ff84cd")
      (lightCyan "#53d6c7")
      (darkMagenta2  "#ed8649")
      (darkBlue2 "#af88eb")
      (lightBlue2 "#bd96fa")
      (lightMagenta2 "#fd9456"))
  (custom-theme-set-faces
   'selenized
   `(default ((t (:background ,bg0 :foreground ,fg0))))
   `(cursor ((t (:background ,fg1))))
   `(hl-line ((t (:background ,bg1))))
   `(show-paren-match-expression ((t (:background ,bg2))))
   `(bold ((t (:weight bold))))
   `(bold-italic ((t (:weight bold :slant italic))))
   `(italic ((t (:slant italic))))
   `(region ((t (:background ,dim0))))
   `(underline ((t (:underline t))))
   `(diff-added ((t (:foreground ,lightGreen :weight bold))))
   `(diff-removed ((t (:foreground ,lightRed :weight bold))))
   `(diff-context ((t (:foreground ,fg1))))
   `(diff-file-header ((t (:foreground ,lightCyan :background nil))))
   `(diff-indicator-added ((t (:foreground ,lightGreen))))
   `(diff-indicator-removed ((t (:foreground ,lightRed))))
   `(diff-header ((t (:foreground ,fg1 :background "#232526"))))
   `(diff-hunk-header ((t (:foreground ,darkBlue2 :background "#232526"))))
   `(escape-glyph ((t (:foreground ,lightYellow))))
   `(minibuffer-prompt ((t (:foreground ,lightCyan))))
   `(font-lock-builtin-face ((t (:foreground ,lightGreen))))
   `(font-lock-comment-face ((t (:foreground ,dim0 :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,dim0 :slant italic))))
   `(font-lock-constant-face ((t (:foreground ,darkMagenta))))
   `(font-lock-doc-face ((t (:foreground ,lightYellow :slant italic))))
   `(font-lock-function-name-face ((t (:foreground ,lightRed :slant italic))))
   `(font-lock-keyword-face ((t (:foreground ,darkCyan))))
   `(font-lock-negation-char-face ((t (:weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground ,lightGreen))))
   `(font-lock-regexp-grouping-backslash ((t (:weight bold))))
   `(font-lock-regexp-grouping-construct ((t (:weight bold))))
   `(font-lock-string-face ((t (:foreground ,lightYellow))))
   `(font-lock-type-face ((t (:foreground ,lightCyan))))
   `(Font-lock-variable-name-face ((t (:foreground ,lightRed))))
   `(font-lock-warning-face ((t (:foreground ,fg1 `:background ,bg1))))
   `(outline-1 ((t (:foreground ,lightYellow))))
   `(outline-2 ((t (:foreground ,lightMagenta2))))
   `(outline-3 ((t (:foreground ,darkMagenta2))))
   `(outline-4 ((t (:foreground ,lightRed))))
   `(outline-5 ((t (:foreground ,darkRed))))
   `(outline-6 ((t (:foreground ,darkBlue2))))
   `(outline-7 ((t (:foreground ,darkCyan))))
   `(outline-8 ((t (:foreground ,lightGreen))))
   `(rainbow-delimiters-depth-1-face ((t (:inherit outline-1))))
   `(rainbow-delimiters-depth-2-face ((t (:inherit outline-2))))
   `(rainbow-delimiters-depth-3-face ((t (:inherit outline-3))))
   `(rainbow-delimiters-depth-4-face ((t (:inherit outline-4))))
   `(rainbow-delimiters-depth-5-face ((t (:inherit outline-5))))
   `(rainbow-delimiters-depth-6-face ((t (:inherit outline-6))))
   `(rainbow-delimiters-depth-7-face ((t (:inherit outline-7))))
   `(rainbow-delimiters-depth-8-face ((t (:inherit outline-8))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground "#BCA3A3"))))
   ;; '(secondary-selection ((t (:background "#272822"))))
   ;; '(shadow ((t (:foreground "#465457"))))
   ))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'selenized)

(provide 'selenized-theme)

;;; selenized-theme.el ends here
